[[entity]]

    [entity.components.Text]
    id = "box"
    text = "BOX: 0/1"
    font_face = { font = "joystix", options.size = 25.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 480, y = 670 }
    pivot = "TopMiddle"
