[[entity]]

    [entity.components.Text]
    id = "level"
    text = "LEVEL 1/1"
    font_face = { font = "joystix", options.size = 25.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 10, y = 652 }
    pivot = "Dot"
