[sprite_sheet.bat]
texture_image = "../assets/textures/bat.png"
sprites = [
    { x = 0,   y = 0,   width = 96, height = 120 }, # Sprite 0
    { x = 96,  y = 0,   width = 96, height = 120 }, # Sprite 1
    { x = 192, y = 0,   width = 96, height = 120 }, # Sprite 2
    { x = 288, y = 0,   width = 96, height = 120 }, # Sprite 3
    { x = 384, y = 0,   width = 96, height = 120 }, # Sprite 4
    { x = 480, y = 0,   width = 96, height = 120 }, # Sprite 5

    { x = 0,   y = 120, width = 96, height = 120 }, # Sprite 6
    { x = 96,  y = 120, width = 96, height = 120 }, # Sprite 7
    { x = 192, y = 120, width = 96, height = 120 }, # Sprite 8
    { x = 288, y = 120, width = 96, height = 120 }, # Sprite 9
    { x = 384, y = 120, width = 96, height = 120 }, # Sprite 10
    { x = 480, y = 120, width = 96, height = 120 }, # Sprite 11
]

[sprite_sheet.bat.animations.fly1]
time =          [0.0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4]
sprite_number = [    5,   4,   3,   2,   1,   0,   1,   2,   3,   4   ]

[sprite_sheet.bat.animations.fly2]
time =           [0.0, 0.2, 0.4, 0.6, 0.8,  1.0]
sprite_number =  [    6,   7,   8,   9,   10   ]
