[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 320, height = 240, color = [00, 00, 00, 255] } #RGBA format

    [entity.components.Transform]
    translation = { x = 320.0, y = 240.0 }
    depth = -1.0


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bat"
    sprite_number = 0

    [entity.components.Transform]
    translation = { x = 320.0, y = 240.0 }

    [entity.components.AnimationControl]
    sprite_sheet_name = "bat"
    animation_name = "fly"
    end.type = "Loop"