[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 1000, height = 800, color = [0, 0, 0, 255] }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }
    depth = 1.0


[[entity]]

    [entity.components.Text]
    id = "score_difficulty"
    text = "NORMAL"
    font_face = { font = "joystix", options.size = 40.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 770 }


[[entity]]

    [entity.components.Text]
    id = "score1"
    text = "1. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 680 }


[[entity]]

    [entity.components.Text]
    id = "score2"
    text = "2. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 600 }


[[entity]]

    [entity.components.Text]
    id = "score3"
    text = "3. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 520 }


[[entity]]

    [entity.components.Text]
    id = "score4"
    text = "4. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 440 }


[[entity]]

    [entity.components.Text]
    id = "score5"
    text = "5. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 360 }


[[entity]]

    [entity.components.Text]
    id = "score6"
    text = "6. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 280 }


[[entity]]

    [entity.components.Text]
    id = "score7"
    text = "7. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 200 }


[[entity]]

    [entity.components.Text]
    id = "score8"
    text = "8. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 120 }


[[entity]]

    [entity.components.Text]
    id = "score9"
    text = "9. AAAAAA 00000"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 500, y = 40 }


[[entity]]

    [entity.components.Text]
    id = "arrow_left"
    text = "\u25c0"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 50, y = 400 }


[[entity]]

    [entity.components.Text]
    id = "arrow_right"
    text = "\u25b6"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 950, y = 400 }
