[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 1000, height = 800, color = [0, 0, 0, 120] }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }
    depth = 1.0


[[entity]]

    [entity.components.Text]
    id = "level_complete"
    text = "LEVEL COMPLETE"
    font_face = { font = "joystix", options.size = 80.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 600 }


[[entity]]

    [entity.components.Text]
    id = "cursor_continue"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 235, y = 400 }


[[entity]]

    [entity.components.Text]
    id = "cursor_main_menu"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 210, y = 250 }


[[entity]]

    [entity.components.Text]
    id = "continue"
    text = "CONTINUE"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 400 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 430, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }

    [entity.components.MouseReactive]
    id = "continue"


[[entity]]

    [entity.components.Text]
    id = "main_menu"
    text = "MAIN MENU"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 250 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 480, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 250.0 }

    [entity.components.MouseReactive]
    id = "main_menu"
