[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 1000, height = 800, color = [0, 0, 0, 120] }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }
    depth = 1.0


[[entity]]

    [entity.components.Text]
    id = "cursor_resume"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 290, y = 550 }


[[entity]]

    [entity.components.Text]
    id = "cursor_main_menu"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 210, y = 400 }


[[entity]]

    [entity.components.Text]
    id = "cursor_exit"
    text = "\u25ba"
    font_face = { font = "hack", options.size = 60.0 }
    color = [255, 255, 255, 0]

    [entity.components.UITransform]
    translation = { x = 340, y = 250 }


[[entity]]

    [entity.components.Text]
    id = "resume"
    text = "RESUME"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 550 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 320, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 550.0 }

    [entity.components.MouseReactive]
    id = "resume"


[[entity]]

    [entity.components.Text]
    id = "main_menu"
    text = "MAIN MENU"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 400 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 480, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 400.0 }

    [entity.components.MouseReactive]
    id = "main_menu"


[[entity]]

    [entity.components.Text]
    id = "exit"
    text = "EXIT"
    font_face = { font = "joystix", options.size = 60.0 }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 500, y = 250 }


[[entity]]

    [entity.components.SpriteRender]
    fill = { width = 220, height = 60 }

    [entity.components.Transform]
    translation = { x = 500.0, y = 250.0 }

    [entity.components.MouseReactive]
    id = "exit"
