[sprite_sheet.background]
texture_image = "assets/textures/background.png"
sprites = [
    { x = 0, y = 0, width = 720, height = 600 },
]

[sprite_sheet.game]
texture_image = "assets/textures/game.png"
sprites = [
    # Blocks
    { x = 0,   y = 0,  width = 64,  height = 32 }, # Sprite 0
    { x = 64,  y = 0,  width = 64,  height = 32 }, # Sprite 1
    { x = 128, y = 0,  width = 64,  height = 32 }, # Sprite 2
    { x = 192, y = 0,  width = 64,  height = 32 }, # Sprite 3
    { x = 256, y = 0,  width = 64,  height = 32 }, # Sprite 4
    { x = 320, y = 0,  width = 64,  height = 32 }, # Sprite 5

    { x = 0,   y = 32, width = 64,  height = 32 }, # Sprite 6
    { x = 64,  y = 32, width = 64,  height = 32 }, # Sprite 7
    { x = 128, y = 32, width = 64,  height = 32 }, # Sprite 8
    { x = 192, y = 32, width = 64,  height = 32 }, # Sprite 9
    { x = 256, y = 32, width = 64,  height = 32 }, # Sprite 10
    { x = 320, y = 32, width = 64,  height = 32 }, # Sprite 11

    { x = 0,   y = 64, width = 64,  height = 32 }, # Sprite 12
    { x = 64,  y = 64, width = 64,  height = 32 }, # Sprite 13
    { x = 128, y = 64, width = 64,  height = 32 }, # Sprite 14
    { x = 192, y = 64, width = 64,  height = 32 }, # Sprite 15
    { x = 256, y = 64, width = 64,  height = 32 }, # Sprite 16
    { x = 320, y = 64, width = 64,  height = 32 }, # Sprite 17

    # Paddle
    { x = 0,   y = 96, width = 144, height = 24 }, # Sprite 18
    # Ball
    { x = 144, y = 96, width = 24,  height = 24 }, # Sprite 19
]
