[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bunker"
    sprite_number = 0

    [entity.components.Transform]
    translation = { x = 200.0, y = 126.0 }
    depth = -0.1

    [entity.components.Bunker]
    pixel_size = 12


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bunker"
    sprite_number = 0

    [entity.components.Transform]
    translation = { x = 500.0, y = 126.0 }
    depth = -0.1

    [entity.components.Bunker]
    pixel_size = 12


[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "bunker"
    sprite_number = 0

    [entity.components.Transform]
    translation = { x = 800.0, y = 126.0 }
    depth = -0.1

    [entity.components.Bunker]
    pixel_size = 12
